### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by XDream8** [XDream8/revanced-creator#6]
- [ ] Add debug option
- [x] workflow: Use custom keystore for all reddit builds
- [X] workflow: Use custom keystore for all twitter builds
- [x] Support Twitter
- [x] Support Reddit
- [x] Support Youtube Music
- [x] Make CI workflow use custom keystore for all builds

**Comment by XDream8** [comment]
# nim rewrite

- [X] Checking deps

- [X] Checking latest revanced-* versions

- [X] Downloading needed revanced-* and youtube

- [ ] Options

- [ ] building revanced
